version: "3.7"
services:

  backend:
    build:
      context: .
      dockerfile: wiki_pedia_node/backend.dockerfile
    platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - ./wiki_pedia_node:/app
    depends_on:
      - postgres
    networks:
      - project_wiki
    
  frontend:
    build:
      context: .
      dockerfile: wiki_view/frontend.dockerfile
    platform: linux/amd64
    ports:
      - 81:3000
    volumes:
      - ./wiki_view:/app
    networks:
      - project_wiki

  postgres:
    container_name: db-wiki
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - 5111:5432
    volumes:
      - db-wiki-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"
    networks:
      - project_wiki

volumes:
  db-wiki-data:


networks:
  project_wiki:
    driver: "bridge"
